### ISSUE TITLE
Src directories in scope view are empty for modules 

### ISSUE THREAD

**Issue by kesarevs** [alexey-anufriev/scopes-manager-intellij-plugin#8] opened 2021-06-15 20:58 UTC
STR:
1. Create new project (for example ktor sample project): File / New / Project / Ktor:
<img width="799" alt="image" src="https://user-images.githubusercontent.com/2447600/122121798-b37f0780-ce34-11eb-96b2-7511fd8a8abd.png">
2. Add the entire project to the scope:
<img width="450" alt="image" src="https://user-images.githubusercontent.com/2447600/122121949-e0331f00-ce34-11eb-93b5-606019b01601.png">
3. Go to the scope view:
<img width="450" alt="image" src="https://user-images.githubusercontent.com/2447600/122122020-f3de8580-ce34-11eb-809c-b36ea31fec18.png">

As you can see on the last screenshot `src` directory in scope view is empty, which is not true.

**Comment by alexey-anufriev** [comment] 2021-06-15 21:09
hi @kesarevs, thank you for reporting this. I just reproduced this locally. I will work on solving the problem.

**Comment by alexey-anufriev** [comment] 2022-12-06 00:44
This seems to be fixed in 1.9.0. But in fact, I didn't do much in the code, just upgraded the base IDEA version.
Please reopen the issues if it doesn't work still.

**Closed by alexey-anufriev** 2022-12-06 00:44 UTC
